version: '3.8'

services:
  #database section
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  productdb:
    image: mysql:8.0.29

  customerdb:
    image: postgres:alpine3.16

  basketdb:
    image: redis:alpine

  inventorydb:
    image: mongo

  #infrastructure section

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
    
  

 
  #network section
networks:
  default:
   name: microservices
   driver: bridge


  #volumes section
volumes:
  order_data:
    driver_opts:
      device: /f/dulieudocker/microservices/sqlserverdb
      type: none
      o: bind
  product_data:
    driver_opts:
      device: /f/dulieudocker/microservices/mysqldb
      type: none
      o: bind
  customer_data:
    driver_opts:
      device: /f/dulieudocker/microservices/customerdb
      type: none
      o: bind
  portainer_data:
    driver_opts:
      device: /f/dulieudocker/microservices/portainerdb
      type: none
      o: bind
  elasticsearch_data:
    driver_opts:
      device: /f/dulieudocker/microservices/elasticsearchdb
      type: none
      o: bind
  jaeger_data:
    driver_opts:
      device: /f/dulieudocker/microservices/jaegerdb
      type: none
      o: bind
  mongo_data:
    driver_opts:
      device: /f/dulieudocker/microservices/mongodb
      type: none
      o: bind
  pgadmin_data:
    driver_opts:
      device: /f/dulieudocker/microservices/pgadmindb
      type: none
      o: bind